cerad_game__project_game_schedule__list:
    path:  /project/{_project}/game-schedule
    defaults: 
        _controller: cerad_game__project_games__game_schedule_list__controller:action
        _model:      cerad_game__project_games__game_schedule_list__model
        _template: '@CeradGame\ProjectGames\GameScheduleList\GameScheduleIndex.html.twig'
        
# Game Official (singular) implies only one slot
cerad_game__project__game_official__assign_by_user:
    path:  /project/{_project}/game/{_game}/official/{_gameOfficial}/assign-by-user
    defaults:
        _controller: cerad_game__project__game_official__assign_by_user__controller:assignAction
        _model:      cerad_game__project__game_official__assign_by_user__model_factory
        _form:       cerad_game__project__game_official__assign_by_user__form_factory
        _view:       cerad_game__project__game_official__assign_by_user__view_factory
        _template: '@CeradGame/Project/GameOfficial/AssignByUser/views/AssignByUserPage.html.twig'
        _redirect:   cerad_tourn__referee_schedule__show
        _role:       ROLE_USER
        _userPerson: required
