cerad_game__project_game_schedule__list:
    path:  /project/{_project}/game-schedule
    defaults: 
        _controller: cerad_game__project_games__game_schedule_list__controller:action
        _model:      cerad_game__project_games__game_schedule_list__model
        _template: '@CeradGame\ProjectGames\GameScheduleList\GameScheduleIndex.html.twig'
